[CI/CD] Automate Cocoapods deployments in GitHub actions
fattmerchantorg/Fattmerchant-iOS-SDK pull request #77
Opened 2022-08-12 13:45 UTC by muryno

2022-08-12 17:46 UTC, omar-salah-elboredy commented
@muryno where exactly is the deployment to Cocoapods.org step?
I believe that you are only one step away from the deployment, you've done the build and test phases.
You can use this example to help https://github.com/michaelhenry/deploy-to-cocoapods-github-action#example

2022-08-12 17:47 UTC, omar-salah-elboredy requested changes
I think we need to add deployment step

2022-08-13 09:06 UTC, muryno commented
> @muryno where exactly is the deployment to Cocoapods.org step? I believe that you are only one step away from the deployment, you've done the build and test phases. You can use this example to help https://github.com/michaelhenry/deploy-to-cocoapods-github-action#example
<img width="1084" alt="Screenshot 2022-08-13 at 10 04 34" src="https://user-images.githubusercontent.com/26343440/184477001-ccd6c68a-0133-427e-94e8-14558d9086ff.png">


github action have the plugin which I added

2022-08-15 14:08 UTC, thomasvidas approved these changes

2022-08-15 14:08 UTC, thomasvidas commented on .github/workflows/ios.yml
> +    COCOAPODS_TRUNK_TOKEN:
I'll add the trunk token when we're ready to actually auto-deploy the SDK

2022-08-15 14:28 UTC, omar-salah-elboredy approved these changes

2022-08-15 14:41 UTC, merged